trigger:
- main

variables:
  solution: '**/KodotiAzureDevOpsProject_clean.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  artifactName: 'drop'
  packageFile: 'WebApp.zip'

stages:
# ---------------- CI Stage ----------------
- stage: BuildAndTest
  displayName: 'Compilar y Probar'
  jobs:
  - job: Build
    displayName: 'Compilar solución y ejecutar tests'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: NuGetToolInstaller@1

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '6.0.x'  # Asegúrate que tu código es compatible

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: >
          /p:DeployOnBuild=true
          /p:WebPublishMethod=Package
          /p:PackageAsSingleFile=true
          /p:SkipInvalidConfigurations=true
          /p:DesktopBuildPackageLocation=$(Build.ArtifactStagingDirectory)\$(packageFile)
          /p:DeployIisAppPath="Default Web Site"
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        clean: true

    - task: VSTest@2
      displayName: 'Ejecutar pruebas unitarias'
      inputs:
        testAssemblyVer2: |
          **\bin\$(buildConfiguration)\net6.0\KodotiAzureDevOps.Tests.dll
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        searchFolder: '$(System.DefaultWorkingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: '$(artifactName)'
        publishLocation: 'Container'

# ---------------- CD Stage ----------------
- stage: Deploy
  displayName: 'Desplegar en entorno Proyecto'
  dependsOn: BuildAndTest
  condition: succeeded()
  jobs:
  - deployment: DeployToVM
    displayName: 'Desplegar a máquina con IIS'
    environment:
      name: 'Proyecto'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: $(artifactName)

          - task: PowerShell@2
            displayName: 'Descomprimir y desplegar en IIS'
            inputs:
              targetType: 'inline'
              script: |
                $zipPath = "$(Pipeline.Workspace)\$(artifactName)\$(packageFile)"
                $outputPath = "C:\inetpub\wwwroot\WebApp"

                if (Test-Path $outputPath) {
                  Remove-Item -Recurse -Force $outputPath
                }

                Expand-Archive -Path $zipPath -DestinationPath $outputPath
                Write-Host "✅ Aplicación desplegada en IIS en $outputPath"
