trigger:
- main

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  artifactName: 'drop'
  packageFile: 'WebApp.zip'

stages:
# ---------------- CI Stage ----------------
- stage: BuildAndTest
  displayName: 'Compilar y Probar'
  jobs:
  - job: Build
    displayName: 'Compilar solución y ejecutar tests'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: NuGetToolInstaller@1

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '6.0.x'  # Actualizado desde 3.1.x

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: >
          /p:DeployOnBuild=true 
          /p:WebPublishMethod=Package 
          /p:PackageAsSingleFile=true 
          /p:SkipInvalidConfigurations=true 
          /p:DesktopBuildPackageLocation="$(Build.ArtifactStagingDirectory)\$(packageFile)" 
          /p:DeployIisAppPa


